[application]

# App (Project) Name
name = "wz-explorer"

# Dioxus App Default Platform
# desktop, web, mobile, ssr
default_platform = "web"

# `build` & `serve` dist path
out_dir = "../../docs"

# resource (public) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = "Shroom WZ"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src"]

# uncomment line below if using Router
# index_on_404 = true

# include `assets` in web platform
[web.resource]

# CSS style file
style = [
    #"css/bootstrap.min.css",
    "https://cdn.jsdelivr.net/npm/daisyui@3.9.2/dist/full.css",

    #"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
]

# Javascript code file
script = []

[web.resource.dev]

# serve: [dev-server] only

# CSS style file
style = []

# Javascript code file
script = [
    "https://cdn.tailwindcss.com"
]
