[application]
name = "wz-explorer"
base_path = "shroom-data"
default_platform = "web"
out_dir = "../../docs"
asset_dir = "public"

[web.app]
title = "wz explorer"
index_on_404 = true

[web.watcher]
reload_html = true
watch_path = ["src"]

[web.resource]
style = [
    "https://cdn.jsdelivr.net/npm/daisyui@3.9.2/dist/full.css",
    "https://cdn.tailwindcss.com"
]
script = []

[web.resource.dev]
style = [
]
script = []
